// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASePoK_oAVIQEzAXdPB02X_a7mRubADSo',
    appId: '1:978119720510:web:2d74c6d2fc0b4756311b6f',
    messagingSenderId: '978119720510',
    projectId: 'to-do-a034e',
    authDomain: 'to-do-a034e.firebaseapp.com',
    storageBucket: 'to-do-a034e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEocsCEQ6eK4xf7WDH6J_F7eTKVNyqi2U',
    appId: '1:978119720510:android:c07d80a50f2bfac4311b6f',
    messagingSenderId: '978119720510',
    projectId: 'to-do-a034e',
    storageBucket: 'to-do-a034e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC47nsEcxI0DPedDgRduJdTz6y4FwIP7Bo',
    appId: '1:978119720510:ios:45a8f8b14fed7ee7311b6f',
    messagingSenderId: '978119720510',
    projectId: 'to-do-a034e',
    storageBucket: 'to-do-a034e.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC47nsEcxI0DPedDgRduJdTz6y4FwIP7Bo',
    appId: '1:978119720510:ios:682b825c17ac576e311b6f',
    messagingSenderId: '978119720510',
    projectId: 'to-do-a034e',
    storageBucket: 'to-do-a034e.appspot.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
